### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by mikelolasagasti** [projectdiscovery/blackrock#1]
Package doesn't have license.

I'm trying to package `dnsx` for Fedora. `blackrock` is a dependency for`mapcdir`  that is a dependency for `dnsx`. In order to create the package for Fedora a license is required.

**Comment by ehsandeep** [comment]
thank you for pointing it out @mikelolasagasti, added now.

**Comment by slowmistio** [comment]
Mac M1, error

:40:6: invalid operation: r << (r & 4) (shift count type int64, must be unsigned integer)
# crypto/x509
/usr/local/go/src/crypto/x509/root_cgo_darwin.go:16:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
